name: melton_app
description: App for Melton Foundation Fellows - https://meltonfoundation.org/

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.0
  flutter_markdown: ^0.4.3
  google_sign_in: ^4.5.3
  shared_preferences: '>=0.5.10 <2.0.0'
  searchable_dropdown: ^1.1.3
  google_maps_flutter: ^0.5.33
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  get_it: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/.
    - assets/UN_SDG/.
    - assets/errors/.
    - assets/maps/.
