name: dartfmt CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
#     - name: Install dependencies
#       run: pub get
    - name: Do dartfmt dry-run
      run: dartfmt -n ./ > $DARTFMT_OUTPUT
    - name: Check for non-compliant files
      run: echo $DARTFMT_OUTPUT
