name: Flutter Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flutter_format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      
    - name: Flutter Format
      run: flutter format --dry-run --set-exit-if-changed .
