name: Flutter Test CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Run Flutter tests
      run: flutter test
